[[language]]
name = "python"
language-servers = [ "pyright" ]

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server" ]

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

